# Generated by Django 5.2.10 on 2026-01-18 09:37

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("authentication", "Role")

    roles = [
        "superadmin",
        "admin",
        "manager",
        "sales_representative",
    ]

    for role in roles:
        Role.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_lead_email"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
