# Generated by Django 5.2.10 on 2026-01-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_seed_roles"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Lead",
                ),
            ],
            database_operations=[],
        ),
    ]
