# Generated by Django 5.2.10 on 2026-01-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_reminder_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reminder_sent",
        ),
    ]
