# Generated by Django 5.2.10 on 2026-01-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companysubscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.company'),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='companysubscription',
            table='Company_Subscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='Subscription_Plan',
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Subscription',
            },
        ),
    ]
