# Generated by Django 5.2.10 on 2026-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_companysubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='admin@company.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
