# Generated by Django 5.2.10 on 2026-01-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_company_owner_alter_company_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_id',
            field=models.CharField(default='1', help_text='Public plan identifier (e.g. BASIC_30, PRO_90)', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
