# Generated by Django 5.2.10 on 2026-01-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_companysubscription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='company',
        ),
    ]
