# Generated by Django 5.2.10 on 2026-01-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_companysubscription_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.company'),
            preserve_default=False,
        ),
    ]
