# Generated by Django 5.2.10 on 2026-01-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_companysubscription_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysubscription',
            old_name='starts_at',
            new_name='started_at',
        ),
    ]
