# Generated by Django 5.2.10 on 2026-01-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_rename_starts_at_companysubscription_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='starts_at',
            new_name='started_at',
        ),
    ]
