# Generated by Django 5.2.10 on 2026-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
