# Generated by Django 5.2.10 on 2026-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_company_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
