# Generated by Django 5.2.10 on 2026-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_company_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='reminder_sent_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_sent_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
