# Generated by Django 5.2.10 on 2026-01-27 15:10

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def dedupe_user_subscriptions(apps, schema_editor):
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")
    for user_id in (
        UserSubscription.objects.values_list("user_id", flat=True).distinct().iterator()
    ):
        subs = UserSubscription.objects.filter(user_id=user_id).order_by(
            "-started_at", "-id"
        )
        keep = subs.first()
        if not keep:
            continue
        subs.exclude(id=keep.id).delete()


def backfill_user_subscription_status(apps, schema_editor):
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")
    now = timezone.now()
    for sub in UserSubscription.objects.all().iterator():
        if not sub.is_active:
            status = "expired"
        elif sub.is_trial:
            status = "trial"
        elif sub.expires_at < now:
            status = "expired"
        else:
            status = "active"
        UserSubscription.objects.filter(id=sub.id).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0016_alter_company_table"),
        ("workspaces", "0007_delete_workspacecounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("trial", "Trial"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="ends_at",
            new_name="expires_at",
        ),
        migrations.RunPython(dedupe_user_subscriptions, migrations.RunPython.noop),
        migrations.RunPython(
            backfill_user_subscription_status, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="is_trial",
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="accounts.user",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("trial", "Trial"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("reminder_sent_days", models.JSONField(blank=True, default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_subscription",
            },
        ),
    ]
