# Generated by Django 5.2.10 on 2026-01-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspacemember_invited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_counter',
                'unique_together': {('workspace', 'entity')},
            },
        ),
    ]
