# Generated by Django 5.2.10 on 2026-01-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspacecounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceCounter',
        ),
    ]
