# Generated by Django 5.2.10 on 2026-01-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('deal', 'Deal'), ('lead', 'Lead')], max_length=20)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'entity')},
            },
        ),
    ]
