# Generated by Django 5.2.10 on 2026-01-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_lead'),
        ('subscriptions', '0005_alter_company_owner_alter_company_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='subscriptions.company'),
        ),
    ]
