# Generated by Django 5.2.10 on 2026-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
