# Generated by Django 5.2.10 on 2026-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_trial_ends_at_user_trial_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
