# Generated by Django 5.2.10 on 2026-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailverificationtoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=9812345678, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
