# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('probability', models.PositiveIntegerField(help_text='Probability in percentage')),
                ('pipeline_stage', models.CharField(choices=[('lead', 'Lead'), ('contact_made', 'Contact Made'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='lead', max_length=20)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('display_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('created_from_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_deals', to='leads.lead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['workspace'], name='deals_deala_workspa_495553_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['created_at'], name='deals_deala_created_43237e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['workspace', 'created_at'], name='deals_deala_workspa_4a54fb_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace'], name='deals_workspa_d2bfea_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='deals_created_7fb120_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['assigned_to'], name='deals_assigne_de4f82_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'pipeline_stage'], name='deals_workspa_333a07_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_from_lead'], name='deals_created_0f5f59_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'created_at'], name='deals_workspa_6e6b90_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'assigned_to'], name='deals_workspa_8c3e53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('workspace', 'display_number')},
        ),
    ]
