# Generated by Django 4.0.10 on 2026-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealcontact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dealcontact',
            name='deal_contac_workspa_016f2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='dealcontact',
            name='deal_contac_workspa_ff7438_idx',
        ),
        migrations.AlterField(
            model_name='dealactivity',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('NOTE', 'Note'), ('EMAIL', 'Email'), ('STATUS_CHANGE', 'Status Change'), ('MEETING', 'Meeting'), ('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='dealcontact',
            index=models.Index(fields=['workspace', 'deal'], name='deal_contac_workspa_bae3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dealcontact',
            index=models.Index(fields=['workspace', 'contact'], name='deal_contac_workspa_da1543_idx'),
        ),
    ]
