# Generated by Django 5.2.10 on 2026-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='display_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
