# Generated by Django 5.2.10 on 2026-01-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_display_number'),
        ('workspaces', '0007_delete_workspacecounter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('workspace', 'display_number')},
        ),
    ]
