# Generated by Django 4.0.10 on 2026-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_dealactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealactivity',
            old_name='deescription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='dealactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dealactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
