# Generated by Django 4.0.10 on 2026-02-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_lead_is_converted_alter_lead_status_and_more'),
        ('deals', '0008_rename_deescription_dealactivity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='created_from_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_deals', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'pipeline_stage'], name='deals_workspa_333a07_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_from_lead'], name='deals_created_0f5f59_idx'),
        ),
    ]
