# Generated by Django 4.0.10 on 2026-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_created_from_lead_deal_deals_workspa_333a07_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace'], name='deals_workspa_d2bfea_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='deals_created_7fb120_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['assigned_to'], name='deals_assigne_de4f82_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'created_at'], name='deals_workspa_6e6b90_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'assigned_to'], name='deals_workspa_8c3e53_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['workspace'], name='deals_deala_workspa_495553_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['created_at'], name='deals_deala_created_43237e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['workspace', 'created_at'], name='deals_deala_workspa_4a54fb_idx'),
        ),
    ]
