# Generated by Django 4.0.10 on 2026-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deal_deals_workspa_d2bfea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
