# Generated by Django 4.0.10 on 2026-02-08 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationrule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_execution_logs',
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_conditions',
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field')], max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_actions',
            },
        ),
    ]
