# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('event_name', models.CharField(choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won'), ('deal.stage_changed', 'deal.stage_changed'), ('task.completed', 'task.completed')], max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won'), ('deal.stage_changed', 'deal.stage_changed'), ('task.completed', 'task.completed')], max_length=100)),
                ('target_object_id', models.IntegerField(blank=True, null=True)),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field'), ('rule_execution', 'Rule Execution')], max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='automation.automationrule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_execution_logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_conditions',
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field'), ('rule_execution', 'Rule Execution')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_actions',
            },
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['workspace', 'rule'], name='automation__workspa_e214a4_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['event_type'], name='automation__event_t_ea707c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['idempotency_key'], name='automation__idempot_392af5_idx'),
        ),
    ]
