# Generated by Django 4.0.10 on 2026-02-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
