# Generated by Django 4.0.10 on 2026-02-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
        ('automation', '0003_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecutionlog',
            options={'ordering': ['-executed_at']},
        ),
        migrations.RenameField(
            model_name='automationexecutionlog',
            old_name='message',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='automationexecutionlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='automationexecutionlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='automationexecutionlog',
            name='success',
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='error_trace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='event_type',
            field=models.CharField(default='lead.created', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='target_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='automation.automationrule'),
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['workspace', 'rule'], name='automation__workspa_e214a4_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['event_type'], name='automation__event_t_ea707c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['idempotency_key'], name='automation__idempot_392af5_idx'),
        ),
    ]
