# Generated by Django 4.0.10 on 2026-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_automationexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationaction',
            old_name='params',
            new_name='config',
        ),
        migrations.AddField(
            model_name='automationaction',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='event_name',
            field=models.CharField(default='lead.created', max_length=255),
            preserve_default=False,
        ),
    ]
