# Generated by Django 4.0.10 on 2026-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_rename_params_automationaction_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrule',
            name='trigger',
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field')], default='Assign User', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won')], max_length=100),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='event_name',
            field=models.CharField(choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won')], max_length=255),
        ),
    ]
