# Generated by Django 4.0.10 on 2026-02-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
        ('automation', '0006_remove_automationrule_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automationrule'),
        ),
        migrations.AlterField(
            model_name='automationcondition',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automationrule'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='workspaces.workspace'),
        ),
    ]
