# Generated by Django 4.0.10 on 2026-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_automationaction_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won'), ('deal.stage_changed', 'deal.stage_changed'), ('task.completed', 'task.completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='event_name',
            field=models.CharField(choices=[('lead.created', 'lead.created'), ('lead.status_changed', 'lead.status_changed'), ('deal.created', 'deal.created'), ('deal.won', 'deal.won'), ('deal.stage_changed', 'deal.stage_changed'), ('task.completed', 'task.completed')], max_length=255),
        ),
    ]
