# Generated by Django 4.0.10 on 2026-02-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_automationexecutionlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field'), ('rule_execution', 'Rule Execution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('create_task', 'Create Task'), ('webhook', 'Webhook'), ('update_field', 'Update Field'), ('rule_execution', 'Rule Execution')], max_length=100),
        ),
    ]
