# Generated by Django 5.2.10 on 2026-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
