# Generated by Django 5.2.10 on 2026-01-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leadactivity',
            table='lead_activity',
        ),
    ]
