# Generated by Django 5.2.10 on 2026-01-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadactivityattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lead-activity/'),
        ),
    ]
