# Generated by Django 5.2.10 on 2026-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_leadactivityattachment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadactivity',
            name='attachment',
        ),
    ]
