# Generated by Django 5.2.10 on 2026-01-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_display_number'),
        ('workspaces', '0007_delete_workspacecounter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('workspace', 'display_number')},
        ),
    ]
