# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leads/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='leads/documents/')),
                ('display_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('unqualified', 'Unqualified'), ('lost', 'Lost')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('event', 'Event'), ('cold_call', 'Cold Call'), ('other', 'Other')], default='WEBSITE', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_converted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lead-activities/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'lead_activity',
                'ordering': ['-created_at', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='lead-activity/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.leadactivity')),
            ],
            options={
                'db_table': 'lead_activity_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['is_completed'], name='lead_activi_is_comp_97771a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'due_date'], name='lead_activi_workspa_a1a246_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'is_completed'], name='lead_activi_workspa_1085d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'created_at'], name='lead_activi_workspa_b7ec46_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['first_name', 'last_name'], name='leads_first_n_6baaef_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_email_554d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_converted'], name='leads_is_conv_124d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'created_at'], name='leads_workspa_911af9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'source'], name='leads_status_ecb5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'is_converted'], name='leads_workspa_9c31bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'status'], name='leads_workspa_7a07cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('workspace', 'display_number')},
        ),
    ]
