# Generated by Django 4.0.10 on 2026-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('NOTE', 'Note'), ('EMAIL', 'Email'), ('STATUS_CHANGE', 'Status Change'), ('MEETING', 'Meeting'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('status_change', 'Status Change'), ('task', 'Task')], max_length=20),
        ),
    ]
