# Generated by Django 5.2.10 on 2026-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadactivity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
