# Generated by Django 5.2.10 on 2026-01-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_created_by_lead_document_lead_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead-activity/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.leadactivity')),
            ],
        ),
    ]
