# Generated by Django 5.2.10 on 2026-01-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_leads_first_n_6baaef_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leadactivityattachment',
            table='lead_activity_attachment',
        ),
    ]
