# Generated by Django 5.2.10 on 2026-01-21 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_leadactivityattachment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivityattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadactivityattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
