# Generated by Django 5.2.10 on 2026-01-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_workspace_leadactivity_workspace'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace'),
            preserve_default=False,
        ),
    ]
