# Generated by Django 5.2.10 on 2026-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_workspace_alter_leadactivity_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='display_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
