# Generated by Django 5.2.10 on 2026-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_lead_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
