# Generated by Django 4.0.10 on 2026-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
