# Generated by Django 4.0.10 on 2026-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_leadactivity_completed_at_leadactivity_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at', 'due_date']},
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'due_date'], name='lead_activi_workspa_a1a246_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'is_completed'], name='lead_activi_workspa_1085d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['workspace', 'created_at'], name='lead_activi_workspa_b7ec46_idx'),
        ),
    ]
