# Generated by Django 4.0.10 on 2026-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_leadactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lead-activities/'),
        ),
    ]
