# Generated by Django 4.0.10 on 2026-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_leadactivity_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('unqualified', 'Unqualified'), ('lost', 'Lost')], default='NEW', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'is_converted'], name='leads_workspa_9c31bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'status'], name='leads_workspa_7a07cd_idx'),
        ),
    ]
