# Generated by Django 4.0.10 on 2026-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_lead_is_converted_alter_lead_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_converted'], name='leads_is_conv_124d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'created_at'], name='leads_workspa_911af9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['is_completed'], name='lead_activi_is_comp_97771a_idx'),
        ),
    ]
