# Generated by Django 5.2.10 on 2026-01-19 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_email_company_company_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='companysubscription',
            table='company_subscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription_plan',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='user_subscription',
        ),
    ]
