# Generated by Django 5.2.10 on 2026-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_remove_companysubscription_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
