# Generated by Django 5.2.10 on 2026-01-18 10:36

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    mapping = {
        "superadmin": "SuperAdmin",
        "admin": "Admin",
        "manager": "Manager",
        "sales_representative": "Sales Representative",
    }

    for old, new in mapping.items():
        Role.objects.filter(name=old).update(name=new)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
    ]

    operations = [
    ]
