# Generated by Django 5.2.10 on 2026-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
