# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_executions', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('leads_created_via_automation', models.IntegerField(default=0)),
                ('deals_won_via_automation', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'automation_analytics',
            },
        ),
        migrations.CreateModel(
            name='DealAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_deals', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('won_deals', models.IntegerField(default=0)),
                ('won_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lost_deals', models.IntegerField(default=0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('leads_converted', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_leads_qualified', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deal_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deals_created', models.IntegerField(default=0)),
                ('deals_closed', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activities_completed', models.IntegerField(default=0)),
                ('leads_converted', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
    ]
