# Generated by Django 4.0.10 on 2026-02-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0008_rename_deescription_dealactivity_description_and_more'),
        ('workspaces', '0007_delete_workspacecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deals_created', models.IntegerField()),
                ('deals_closed', models.IntegerField()),
                ('revenue_generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activities_compoleted', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'user_analytics',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DealAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_leads', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('won_deals', models.IntegerField()),
                ('won_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lost_deals', models.IntegerField()),
                ('pipeline_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='deals.deal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_analytics', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'deal_analytics',
                'unique_together': {('deal', 'date')},
            },
        ),
    ]
