# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='dealanalytics',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_analytics', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='automationanalytics',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_analytics', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user', 'date'], name='user_analyt_user_id_d0c1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['workspace', 'date'], name='user_analyt_workspa_5d33de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranalytics',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dealanalytics',
            unique_together={('workspace', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='automationanalytics',
            unique_together={('workspace', 'date')},
        ),
    ]
