# Generated by Django 4.0.10 on 2026-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealanalytics',
            old_name='total_leads',
            new_name='total_deals',
        ),
        migrations.RenameField(
            model_name='useranalytics',
            old_name='activities_compoleted',
            new_name='activities_completed',
        ),
        migrations.AlterUniqueTogether(
            name='dealanalytics',
            unique_together={('workspace', 'date')},
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user', 'date'], name='user_analyt_user_id_d0c1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['workspace', 'date'], name='user_analyt_workspa_5d33de_idx'),
        ),
    ]
