# Generated by Django 4.0.10 on 2026-02-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_total_leads_dealanalytics_total_deals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealanalytics',
            name='deal',
        ),
    ]
