# Generated by Django 4.0.10 on 2026-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_dealanalytics_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealanalytics',
            name='lost_deals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealanalytics',
            name='pipeline_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dealanalytics',
            name='total_deals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealanalytics',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dealanalytics',
            name='won_deals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealanalytics',
            name='won_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='useranalytics',
            name='activities_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useranalytics',
            name='deals_closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useranalytics',
            name='deals_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useranalytics',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
