# Generated by Django 4.0.10 on 2026-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_dealanalytics_lost_deals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealanalytics',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dealanalytics',
            name='leads_converted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealanalytics',
            name='total_leads_qualified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='conversion_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='leads_converted',
            field=models.IntegerField(default=0),
        ),
    ]
