# Generated by Django 4.0.10 on 2026-02-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_delete_workspacecounter'),
        ('analytics', '0005_dealanalytics_conversion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_executions', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('leads_created_via_automation', models.IntegerField(default=0)),
                ('deals_won_via_automation', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_analytics', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_analytics',
                'unique_together': {('workspace', 'date')},
            },
        ),
    ]
