# Generated by Django 4.0.10 on 2026-04-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('duplicate_handling', models.CharField(choices=[('create', 'Always create new lead'), ('update', 'Update existing lead'), ('configurable', 'Smart match email/phone')], default='configurable', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox')], max_length=20)),
                ('options', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('map_to_lead_field', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('email', 'Email'), ('phone', 'Phone'), ('company', 'Company'), ('job_title', 'Job Title'), ('notes', 'Notes'), ('none', 'No Mapping')], default='none', max_length=50)),
                ('assignment_type', models.CharField(choices=[('none', 'No auto assignment'), ('fixed', 'Assign to fixed user'), ('round_robin', 'Round robin')], default='none', max_length=20)),
                ('round_robin_index', models.PositiveIntegerField(default=0)),
                ('fixed_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fixed_assignments', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
                ('round_robin_users', models.ManyToManyField(blank=True, related_name='form_round_robin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_fields',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'form_submissions',
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formsubmission')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'form_responses',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='form_submis_form_id_01095c_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['workspace', 'submitted_at'], name='form_submis_workspa_f2f89d_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['lead'], name='form_submis_lead_id_3cedd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('submission', 'field')},
        ),
    ]
