# Generated by Django 4.0.10 on 2026-02-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='assignment_type',
            field=models.CharField(choices=[('none', 'No auto assignment'), ('fixed', 'Assign to fixed user'), ('round_robin', 'Round robin')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='formfield',
            name='fixed_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fixed_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfield',
            name='map_to_lead_field',
            field=models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('email', 'Email'), ('phone', 'Phone'), ('company', 'Company'), ('job_title', 'Job Title'), ('notes', 'Notes'), ('none', 'No Mapping')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='formfield',
            name='round_robin_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='round_robin_users',
            field=models.ManyToManyField(blank=True, related_name='form_round_robin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='duplicate_handling',
            field=models.CharField(choices=[('create', 'Always create new lead'), ('update', 'Update existing lead'), ('configurable', 'Smart match email/phone')], default='configurable', max_length=20),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='form_submis_form_id_01095c_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['lead'], name='form_submis_lead_id_3cedd4_idx'),
        ),
    ]
