# Generated by Django 4.0.10 on 2026-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formfield_assignment_type_formfield_fixed_assignee_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['workspace', 'submitted_at'], name='form_submis_workspa_f2f89d_idx'),
        ),
    ]
