# Generated by Django 4.0.10 on 2026-02-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0007_delete_workspacecounter'),
        ('forms', '0003_formsubmission_form_submis_workspa_f2f89d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterModelTable(
            name='formresponse',
            table='form_responses',
        ),
    ]
