# Generated by Django 4.0.10 on 2026-02-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formresponse_created_by_formresponse_workspace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('submission', 'field')},
        ),
    ]
